import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="favicon.svg" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, target-densityDpi=device-dpi, minimal-ui"
        />
        <title>Erdenedari Ch</title>
        <meta property="og:title" content="Erdenedari Ch" />
        <meta name="description" content="Erdenedari Ch 3D Portfolio" />
        <meta property="og:description" content="Erdenedari Ch 3D Portfolio" />
        <meta
          property="og:url"
          content="https://erdenedari-portfolio-qsim.vercel.app/"
        />
        <meta
          property="og:image"
          content="https://private-user-images.githubusercontent.com/107394167/363201829-e1a22fdc-caf3-439d-9e51-956f436145dd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMjY4MjcsIm5iZiI6MTcyNTAyNjUyNywicGF0aCI6Ii8xMDczOTQxNjcvMzYzMjAxODI5LWUxYTIyZmRjLWNhZjMtNDM5ZC05ZTUxLTk1NmY0MzYxNDVkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQxNDAyMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYTc4OGIzNTlkMDc1ZDQzZTZiMzYzNjgzYzUyNDFlNWQ4NDgyYmEzMzkwZjA1OTk3Njc2YzUxNzgxNWMzMjM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pz0WmSDbu0qG0nKMevqbado81esqxd5BaAkujJzOdfQ"
        />
        <meta name="twitter:card" content="summary" />
      </head>
      <body style={{ backgroundColor: "#7B57B1" }}>{children}</body>
    </html>
  );
}
