import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="favicon.svg" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, target-densityDpi=device-dpi, minimal-ui"
        />
        <title>Erdenedari Ch</title>
        <meta property="og:title" content="Erdenedari Ch" />
        <meta name="description" content="Erdenedari Ch 3D Portfolio" />
        <meta property="og:description" content="Erdenedari Ch 3D Portfolio" />
        <meta
          property="og:url"
          content="https://erdenedari-portfolio-qsim.vercel.app/"
        />
        <meta
          property="og:image"
          content="https://github-production-user-asset-6210df.s3.amazonaws.com/107394167/363192726-dc3dfe44-6ff9-4b15-8dde-b39a107963a3.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20240830%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240830T134600Z&X-Amz-Expires=300&X-Amz-Signature=9233290adff869a3f9530ec96ca36e14d2b885e9997eea3e1aeacd1a46df8db5&X-Amz-SignedHeaders=host&actor_id=107394167&key_id=0&repo_id=838386968"
        />
        <meta name="twitter:card" content="summary" />
      </head>
      <body style={{ backgroundColor: "#7B57B1" }}>{children}</body>
    </html>
  );
}
